[package]
name = "ruccbot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
rand = "0.8.5"
tokio = { version = "1.36.0", features = ["full"] }
regex = "1.10.3"
lazy_static = "1.4.0"
